"""Secure a freshly initialized local MySQL instance and create local app secrets.

This recovery-only bootstrap refuses to overwrite any existing configuration.
It expects a new MySQL instance whose root@localhost account still has the empty
password produced by ``mysqld --initialize-insecure``.
"""

from __future__ import annotations

import os
import secrets
import subprocess
from datetime import datetime
from pathlib import Path

import pymysql
from werkzeug.security import generate_password_hash


ROOT = Path(__file__).resolve().parents[1]
USER_PROFILE = Path(os.environ["USERPROFILE"])
ENV_PATH = ROOT / ".env"
MYSQL_DIR = USER_PROFILE / "mysql"
ADMIN_CNF_PATH = MYSQL_DIR / "admin.cnf"
CREDENTIALS_PATH = ROOT.parent / f"{ROOT.name}_RECOVERY_CREDENTIALS.txt"
APP_USER = "ieee_app"
VIEWER_USER = "viewer"
ADMIN_USER = "admin"


def _refuse_existing(paths: list[Path]) -> None:
    existing = [str(path) for path in paths if path.exists()]
    if existing:
        raise SystemExit("Refusing to overwrite existing local configuration: " + ", ".join(existing))


def _write_exclusive(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def _restrict_to_current_user(path: Path) -> None:
    username = os.environ["USERNAME"]
    subprocess.run(
        ["icacls", str(path), "/inheritance:r", "/grant:r", f"{username}:(F)"],
        check=True,
        capture_output=True,
        text=True,
    )


def main() -> None:
    _refuse_existing([ENV_PATH, ADMIN_CNF_PATH, CREDENTIALS_PATH])

    app_password = secrets.token_urlsafe(36)
    root_password = secrets.token_urlsafe(40)
    viewer_password = secrets.token_urlsafe(18)
    admin_password = secrets.token_urlsafe(18)
    app_secret = secrets.token_hex(32)

    env_content = f"""# Generated by scripts/bootstrap_local_recovery.py. Never commit this file.
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER={APP_USER}
DB_PASSWORD={app_password}
DB_NAME=ieee_repo

AUTH_USERNAME={VIEWER_USER}
AUTH_PASSWORD_HASH={generate_password_hash(viewer_password)}
ADMIN_USERNAME={ADMIN_USER}
ADMIN_PASSWORD_HASH={generate_password_hash(admin_password)}
APP_SECRET_KEY={app_secret}
SESSION_COOKIE_SECURE=0
TEMPLATES_AUTO_RELOAD=1

YONSEI_ID=
YONSEI_PW=
ZOTERO_USER_ID=
ZOTERO_API_KEY=
IEEE_API_KEY=
OPENALEX_API_KEY=
CROSSREF_MAILTO=
"""
    admin_cnf = f"""[client]
host=localhost
port=3306
user=root
password={root_password}
default-character-set=utf8mb4
"""
    credentials = f"""IEEE Paper Server recovery credentials
Created: {datetime.now().astimezone().isoformat()}

Viewer URL: http://127.0.0.1:5001/
Viewer username: {VIEWER_USER}
Viewer password: {viewer_password}

Administrator username: {ADMIN_USER}
Administrator password: {admin_password}

The application DB password is stored only in:
  {ENV_PATH}

The MySQL root password is stored only in:
  {ADMIN_CNF_PATH}
Use it with mysql --defaults-extra-file=<that path>.

After recording the two web passwords in a password manager, keep this file
offline or remove it manually. This script never removes it automatically.
"""

    connection = pymysql.connect(
        host="localhost",
        port=3306,
        user="root",
        password="",
        autocommit=True,
        charset="utf8mb4",
    )
    try:
        with connection.cursor() as cursor:
            for host in ("localhost", "127.0.0.1"):
                cursor.execute(
                    f"CREATE USER IF NOT EXISTS '{APP_USER}'@'{host}' IDENTIFIED BY %s",
                    (app_password,),
                )
                cursor.execute(
                    f"ALTER USER '{APP_USER}'@'{host}' IDENTIFIED BY %s",
                    (app_password,),
                )
                cursor.execute(
                    f"GRANT ALL PRIVILEGES ON ieee_repo.* TO '{APP_USER}'@'{host}'"
                )

        _write_exclusive(ENV_PATH, env_content)
        _write_exclusive(ADMIN_CNF_PATH, admin_cnf)
        _write_exclusive(CREDENTIALS_PATH, credentials)
        for path in (ENV_PATH, ADMIN_CNF_PATH, CREDENTIALS_PATH):
            _restrict_to_current_user(path)

        with connection.cursor() as cursor:
            cursor.execute(
                "ALTER USER 'root'@'localhost' IDENTIFIED BY %s", (root_password,)
            )
    finally:
        connection.close()

    print(f"Local app configuration: {ENV_PATH}")
    print(f"MySQL administrator option file: {ADMIN_CNF_PATH}")
    print(f"One-time web credentials: {CREDENTIALS_PATH}")


if __name__ == "__main__":
    main()
